added growing input field on comment section
Oogway-Technologies/oogway-pilot pull request #105
Opened 2022-02-14 16:10 UTC by ihtisham1211

2022-02-14 20:40 UTC, EandrewJones requested changes

2022-02-14 20:40 UTC, EandrewJones commented on styles/feed.js
> +        'inline-flex rounded-[10px] items-center py-2 px-2 md:px-5 lg:w-96 xl:w-96 \
Please change this line to:
`inline-flex rounded-[10px] items-center py-2 pl-2 pr-1 md:pl-5 md:pr-3 lg:w-96 xl:w-96`

so the px-2 and md:px-5 are decomposed into different left and right margins.

2022-02-14 20:40 UTC, EandrewJones commented on styles/feed.js
>          'p-sm rounded-[20px] justify-self-end text-neutral-700 dark:text-neutralDark-150 \
Please add a `ml-1` to the imageButton style.

2022-02-15 19:59 UTC, FedericoCampe8 submitted a review, later dismissed

2022-02-15 20:09 UTC, merged